[package]
name = "astro_calc"
version = "0.1.0"
authors = ["Ryan Leach <ryan.n.leach@gmail.com>"]

description = "Astronomical Algorithms"
keywords = ["Astronomy", "Science"]
license = "BSD-3-Clause"
readme = "README.md"

[dependencies]
lazy_static = "0.1.*"
